### ISSUE TITLE
Plans to specify license for `evm-indexer` ..?

### ISSUE THREAD

**Issue by shunkakinoki** [eabz/evm-indexer#6]
Hi kindynosmx and @eabz !

Thank you for providing such a superb work & extremely valuable codebase!
Really enjoying it, 
Would you mind specifying a particular license for the repository, or any plans to whether or not to do if possible

I feel like it would be a contribution worthwhile to the ecosystem if others could built upon.

**Comment by eabz** [comment]
Hey @shunkakinoki thanks for your interest to contribute to the indexer. 

Just added an MIT license (https://github.com/kindynosmx/evm-indexer/commit/b92e52c8c5ede21fd59cce1c5bd601a873eb464f) feel free to use it however you want.

**Comment by shunkakinoki** [comment]
Thank you so much @eabz, you're a beast 🫡

Would love to contribute as I progress
